import { Conversation } from './chat.types';

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    title: 'Energy consumption analysis',
    userId: 'user-1',
    createdAt: '2026-02-25T10:00:00Z',
    updatedAt: '2026-02-25T10:45:00Z',
    messages: [
      {
        id: 'msg-1',
        conversationId: 'conv-1',
        sequence: 1,
        role: 'USER',
        type: 'CHAT',
        content: 'Can you analyze our energy consumption patterns for the last quarter?',
        format: 'TEXT',
        createdAt: '2026-02-25T10:00:00Z',
      },
      {
        id: 'msg-2',
        conversationId: 'conv-1',
        sequence: 2,
        role: 'ASSISTANT',
        type: 'CHAT',
        content:
          "I'll analyze your energy consumption for Q4. Based on the available data:\n\n**Key Findings:**\n- Total consumption: **1,842 MWh** (↓ 8.3% vs Q3)\n- Peak demand: **124 kW** on Dec 14 at 09:00\n- Lowest consumption week: Nov 25–Dec 1 (holiday period)\n\n**Recommendations:**\n1. Shift heavy loads to off-peak hours (22:00–06:00)\n2. Review HVAC scheduling for Building B\n3. Investigate anomalous spike on December 3rd\n\nWould you like a detailed breakdown by facility?",
        format: 'MARKDOWN',
        createdAt: '2026-02-25T10:01:00Z',
      },
      {
        id: 'msg-3',
        conversationId: 'conv-1',
        sequence: 3,
        role: 'USER',
        type: 'CHAT',
        content: 'Yes, please break it down by facility.',
        format: 'TEXT',
        createdAt: '2026-02-25T10:05:00Z',
      },
      {
        id: 'msg-4',
        conversationId: 'conv-1',
        sequence: 4,
        role: 'ASSISTANT',
        type: 'CHAT',
        content:
          "Here's the breakdown by facility:\n\n| Facility | Consumption (MWh) | vs Q3 | Cost (€) |\n|---|---|---|---|\n| HQ Building A | 742 | ↓ 5% | 88,500 |\n| Building B | 614 | ↓ 12% | 73,200 |\n| Warehouse C | 486 | ↑ 2% | 57,900 |\n\nBuilding B shows the largest improvement, likely due to the LED retrofit completed in October. Warehouse C is trending upward — I recommend a thermal audit.",
        format: 'MARKDOWN',
        createdAt: '2026-02-25T10:06:30Z',
      },
    ],
  },
  {
    id: 'conv-2',
    title: 'Monthly report generation',
    userId: 'user-1',
    createdAt: '2026-02-24T14:00:00Z',
    updatedAt: '2026-02-24T14:22:00Z',
    messages: [
      {
        id: 'msg-5',
        conversationId: 'conv-2',
        sequence: 1,
        role: 'USER',
        type: 'CHAT',
        content: 'Generate the January monthly report for all clients.',
        format: 'TEXT',
        createdAt: '2026-02-24T14:00:00Z',
      },
      {
        id: 'msg-6',
        conversationId: 'conv-2',
        sequence: 2,
        role: 'ASSISTANT',
        type: 'TOOL_CALL',
        content: JSON.stringify({ tool: 'generate_report', args: { month: 'January', year: 2026, scope: 'all_clients' } }),
        format: 'JSON',
        createdAt: '2026-02-24T14:00:05Z',
      },
      {
        id: 'msg-7',
        conversationId: 'conv-2',
        sequence: 3,
        role: 'TOOL',
        type: 'TOOL_RESULT',
        content: JSON.stringify({ status: 'success', reportUrl: '/reports/jan-2026.pdf', clientsProcessed: 47 }),
        format: 'JSON',
        createdAt: '2026-02-24T14:00:45Z',
      },
      {
        id: 'msg-8',
        conversationId: 'conv-2',
        sequence: 4,
        role: 'ASSISTANT',
        type: 'CHAT',
        content:
          'The January 2026 report has been generated successfully!\n\n- **47 clients** processed\n- Report available at `/reports/jan-2026.pdf`\n\nAll reports have been queued for email delivery.',
        format: 'MARKDOWN',
        createdAt: '2026-02-24T14:00:47Z',
      },
    ],
  },
  {
    id: 'conv-3',
    title: 'Anomaly detection query',
    userId: 'user-1',
    createdAt: '2026-02-23T09:30:00Z',
    updatedAt: '2026-02-23T09:35:00Z',
    messages: [
      {
        id: 'msg-9',
        conversationId: 'conv-3',
        sequence: 1,
        role: 'USER',
        type: 'CHAT',
        content: 'Are there any consumption anomalies detected in the last 7 days?',
        format: 'TEXT',
        createdAt: '2026-02-23T09:30:00Z',
      },
      {
        id: 'msg-10',
        conversationId: 'conv-3',
        sequence: 2,
        role: 'ASSISTANT',
        type: 'CHAT',
        content:
          "I've scanned the last 7 days. **2 anomalies** detected:\n\n1. **Feb 20, 03:15** — Warehouse C: 340% spike above baseline (duration: 18 min)\n2. **Feb 22, 11:00** — Building B: consumption 45% below expected (possible meter fault)\n\nShall I raise alerts for the facility managers?",
        format: 'MARKDOWN',
        createdAt: '2026-02-23T09:30:45Z',
      },
    ],
  },
  {
    id: 'conv-4',
    title: 'Forecasting next month demand',
    userId: 'user-1',
    createdAt: '2026-02-20T11:00:00Z',
    updatedAt: '2026-02-20T11:10:00Z',
    messages: [
      {
        id: 'msg-11',
        conversationId: 'conv-4',
        sequence: 1,
        role: 'USER',
        type: 'CHAT',
        content: "Forecast March's energy demand based on historical patterns.",
        format: 'TEXT',
        createdAt: '2026-02-20T11:00:00Z',
      },
      {
        id: 'msg-12',
        conversationId: 'conv-4',
        sequence: 2,
        role: 'ASSISTANT',
        type: 'CHAT',
        content:
          "Based on a 24-month historical baseline, March 2026 forecast:\n\n**Predicted Total: 1,910 MWh** (±5%)\n\n- Week 1: 468 MWh\n- Week 2: 492 MWh\n- Week 3: 497 MWh\n- Week 4: 453 MWh\n\nExpect a slight uptick vs February due to seasonal heating demand. Confidence interval: 85%.",
        format: 'MARKDOWN',
        createdAt: '2026-02-20T11:01:00Z',
      },
    ],
  },
];
